### ISSUE TITLE
Fork, Patch, Rebuild

### ISSUE THREAD

**Issue by flyingflo** [imgrant/AuxHR#1]
Hi,

Thanks for publishing the source!
I forked, patched (removed FIT recording), and rebuilt (add support for newer devices) this data field, recently.
I'll try it for watching the heart rate of training partners and probably do better with pacing them.
Do you mind if I publish the fork in the CIQ store, when finished?

Thanks,
Florian

**Comment by imgrant** [comment]
Hi, feel free to publish. It's a long time since I did anything with CIQ, but I would also be happy to pull your changes in here (apart from the removal of FIT recording, that was the point for me, but the other people's sensors is an interesting use case!)
